
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Tables } from '../../lib/types';

const SUPABASE_URL = "https://njyupntvyejykzrwxgkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qeXVwbnR2eWVqeWt6cnd4Z2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTM2MTUsImV4cCI6MjA1ODc2OTYxNX0.VDLbkWd2CMk6TyhpAFG7gw6GmWcAEPaxJ9XtX8fGyp0";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export type { Tables };
